- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/pages/home.html.erb
Really ugly buttons. I tried to compartmentalise (?) not sure if this is the right word for it but these buttons are in pages home.html
> Added some ugly orange buttons i'm sorry whoever fixes this mess

- app/models/chatroom.rb
- app/models/criteria.rb
- app/models/criterium.rb
- app/models/event.rb
- app/models/itinerary.rb
- app/models/itinerary_criteria.rb
- app/models/user.rb
Created the has_many through associations
> created the model associations

- app/assets/stylesheets/components/_buttons.scss
- app/views/pages/home.html.erb
Minor additions to .btn-orange, and added orange btn hover styles
> fixed orange btn styles

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_form.scss
- app/controllers/itineraries_controller.rb
- app/models/chatroom.rb
- app/models/itinerary.rb
- app/views/itineraries/_itinerary_form.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220609091751_create_active_storage_tables.active_storage.rb
- db/schema.rb
> Create/travel itinerary#new#create

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/chatrooms/_show.scss
- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/views/chatrooms/show.html.erb
- app/views/layouts/application.html.erb
created and styled the chatroom, havent apply action cable yet
> Create chatroom messages

- app/assets/stylesheets/pages/chatrooms/_show.scss
- app/views/chatrooms/show.html.erb
have attempted to style the chatroom to be similar to figma
> Style chatroom

- app/controllers/chatrooms_controller.rb
- app/javascript/controllers/chatroom_summary_controller.js
- app/views/chatrooms/index.html.erb
- app/views/itineraries/_tab_member.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
created an index method for chatroom controller to view all chats by the user
> Amend chat sidebar

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_links.scss
- app/views/itineraries/index.html.erb
- app/views/shared/_navbar.html.erb
1. Displayed all itineraries in the intineraries#index page
2. Created itinerary cards
3. Got random unplash picture for the itinerary image based on the search terms of  'trip' and the itinerary title
4. Positioned elements within card
5. Card hover effects
Note: 
- favoriting itineraries with the heart icon is not possible yet
> View all itineraries

- app/assets/stylesheets/components/_navbar.scss
Made navbar navlink font size smaller based on feedback from yesterday's surprise demo.
> Reduced nav link font size from 24px to 18px

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/itineraries/index.html.erb
- app/views/pages/home.html.erb
Removed the lorem ipsum placeholder and added:
1. Simple website intro
2. 3 itinerary cards showing the latest first
Also made some font sizes smaller cos it was huge before.
Here's a screenshot:
> Remove homepage lorem placeholder

- app/controllers/chatrooms_controller.rb
- app/policies/chatroom_policy.rb
- app/views/chatrooms/new.html.erb
- app/views/itineraries/_tab_member.html.erb
- config/routes.rb
able to create a new chat when clicking on the 'send a message to organiser' in the itinerary show page
> Link send message to chatroom

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/chatrooms/_index.scss
- app/assets/stylesheets/pages/chatrooms/_show.scss
- app/controllers/chatrooms_controller.rb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
amended the chatroom show page:
1. side bar to contain the information about the group
2. added some colour to the chat box
> Amend chatroom show page

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/chatrooms/_index.scss
- app/controllers/chatrooms_controller.rb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
amended the chatrooms index page that shows all the chatrooms from the current user.
may need further design improvement on this!
> Amend chatrooms index page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/controllers/itineraries_controller.rb
- app/javascript/controllers/navbar_controller.js
- app/javascript/controllers/search_itineraries_controller.js
- app/views/itineraries/_list.html.erb
- app/views/itineraries/index.html.erb
On the itineraries#index page - Made a search bar using JS to search on the itinerary title
> Itineraries index search bar

- app/assets/stylesheets/components/_itinerary_tabs.scss
- app/controllers/itineraries_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/itineraries/_itineraries_tabs.html.erb
- app/views/itineraries/_itinerary_accordion.html.erb
- db/seeds.rb
Added a test user bika so that we don't have to keep finding. Has customised dates and timed events for testing
> Added tabs styling, and created default user bika for testing

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/users/_show.scss
- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/itineraries/_tab_member.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/policies/user_policy_test.rb
this is the user profile page, can be follower or organiser, both users will have the same view page.
> Follower profile page

- app/assets/stylesheets/pages/chatrooms/_show.scss
- app/controllers/chatrooms_controller.rb
- app/views/chatrooms/show.html.erb
amended the broken link when selecting on the direct message link, also amended the style for the chatroom
> Amend chatroom

- app/assets/stylesheets/components/_itinerary-accordion.scss
- app/controllers/itineraries_controller.rb
- app/javascript/controllers/reverse_geocode_controller.js
- app/views/itineraries/_itineraries_tabs.html.erb
- app/views/itineraries/_itinerary_accordion.html.erb
- app/views/itineraries/holding.html.erb
Reverse geocoded using mapbox to get address from generic name. Added styling to the modal
> Reverse geocode

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/itineraries_controller.rb
Changed the fonts to Poppins and Roboto
> Changed fonts to Poppins and Roboto

- app/controllers/itineraries_controller.rb
- app/models/itinerary.rb
- app/policies/itinerary_policy.rb
- app/views/itineraries/_itineraries_tabs.html.erb
Tab view is filtered depending on whether the user is accepted into the group or not.
> Added pundit to restrict view depending on user

- app/assets/stylesheets/components/_navbar.scss
- app/controllers/application_controller.rb
- app/controllers/itineraries_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
Problem: Navbar text color was white on the transparent navbar, but users might upload dark images which make the black text difficult to see.
I changed the the navbar text to black for pages where there might be a dark background
> Changed navbar text to black on pages where there might be a dark banner

- app/assets/stylesheets/components/_banner.scss
- app/controllers/itineraries_controller.rb
- app/views/itineraries/index.html.erb
Added a banner to the all trips page in an attempt to look aesthetic
> Added banner to Itineraries#index page

- app/assets/stylesheets/components/_chatroom.scss
- app/controllers/chatrooms_controller.rb
- app/views/chatrooms/_chatbox.html.erb
- app/views/chatrooms/index.html.erb
have style the chat in accordance to figma, when you hover over the name it will be orange
> Add figma to chat design

- app/views/itineraries/_list.html.erb
changed the card styles in the itineraries index page to match that of the hompage's
> Changed card styles in index page to match that of the homepage

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/models/user.rb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20220616023131_create_reviews.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/reviews_controller_test.rb
- test/models/review_test.rb
created the reviews model and reviews can be displayed on the user profile page.
> Create reviews for users

- app/assets/stylesheets/components/_badges.scss
- app/assets/stylesheets/components/_index.scss
- app/channels/my_notification_badge_channel.rb
- app/controllers/itinerary_users_controller.rb
- app/controllers/notifications_controller.rb
- app/javascript/controllers/notification_badge_subscription_controller.js
- app/policies/notification_policy.rb
- app/views/itineraries/_current_travellers.html.erb
- app/views/itineraries/_each_current_traveller.html.erb
- app/views/notifications/_badge-number.html.erb
- app/views/notifications/_notification-list.html.erb
- app/views/notifications/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20220616022232_add_type_to_notifications.rb
- db/migrate/20220616031912_add_default_false_to_read_in_notifications.rb
- db/schema.rb
- test/channels/my_notification_badge_channel_test.rb
- test/policies/notification_policy_test.rb
1. Actioncable notification badge works
Future: Need to include chat notifications within notifications
> Notification badge

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/controllers/itineraries_controller.rb
- app/javascript/controllers/search_itineraries_controller.js
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/models/event.rb
- app/models/itinerary.rb
- app/views/itineraries/index.html.erb
- app/views/pages/_banner.html.erb
- db/migrate/20220615154258_add_start_date_to_itineraries.rb
- db/migrate/20220615154337_add_end_date_to_itineraries.rb
- db/schema.rb
- package.json
- yarn.lock
1. Created homepage search bar to search by destination (country), start_date & end_date.
2. Added start_date and end_date columns for itineraries table (migrations)
3. Added Flatpickr JS library to enable picking of dates
> Search itinerary by date

- app/views/shared/_navbar.html.erb
Removed the plan trip btn from navbar
> Removed plan trip btn from navbar

- app/assets/stylesheets/components/_chatroom.scss
- app/controllers/chatrooms_controller.rb
- app/javascript/controllers/chatbox_controller.js
- app/javascript/controllers/chatroom_subscription_controller.js
- app/views/chatrooms/_chatbox.html.erb
- app/views/chatrooms/index.html.erb
- db/schema.rb
> Amend chat box view

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
recreated the chum logo in the navbar
> changed nav bar logo

- app/views/itineraries/_req-to-join-button.html.erb
- app/views/itineraries/_tabs.html.erb
> ok push don't worry i will fix the button

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_toggle.scss
- app/channels/notification_dropdown_channel.rb
- app/controllers/itinerary_users_controller.rb
- app/controllers/notifications_controller.rb
- app/javascript/controllers/notification_badge_subscription_controller.js
- app/javascript/controllers/notification_dropdown_subscription_controller.js
- app/javascript/controllers/toggle_controller.js
- app/models/itinerary.rb
- app/models/notification.rb
- app/models/notification_initiator.rb
- app/views/itineraries/_published-toggle-on-member-page.html.erb
- app/views/itineraries/_published-toggle.html.erb
- app/views/shared/_each-notification-row.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_notification-dropdown.html.erb
- config/routes.rb
- db/migrate/20220618012635_create_notification_initiators.rb
- db/schema.rb
- db/seeds.rb
- test/channels/notification_dropdown_channel_test.rb
- test/models/notification_initiator_test.rb
> Notification dropdown

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/events/_event_form.html.erb
- app/views/itineraries/_itinerary_form.html.erb
- app/views/itineraries/_list.html.erb
- app/views/pages/_cards.html.erb
- db/seeds.rb
**Standardized the buttons on the forms to be purple and w-100
Made the form field labels to be all bolded**
**Small bug fix:**
Came across a bug. If a user chooses to publish an itinerary without events, the home page and itineraries index page would break as the cards could not show the start and end dates. Fixed this by adding the if else back:
> Standardize buttons

- app/assets/stylesheets/pages/users/_show.scss
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
amended the seed file further to add reviews to Raymond and Eunice for the purpose of the demo. 
and to accurately show the numbers in the user profile page.
> Amend user profile page

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/itineraries/_list.html.erb
- app/views/itineraries/index.html.erb
Aligned cards on Iternaries#index page
Also, made the title header bolder, from 500 to 600, as the previous fix made it too thin
> Fix card alignment

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/_banner.html.erb
- app/views/pages/home.html.erb
Added parallax effect to the banner
Gave the intro text a light blue background
> Parallax effect

- app/views/chatrooms/index.html.erb
- db/seeds.rb
> Amend chat room
